### PR TITLE
Ruby 3 support

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Review by mrackwitz — APPROVED** [review]
Happy new year, Sam! 🎆 
TIL about `ruby2_keywords`. What a mess this all became. 😥
I haven't really touched Ruby 3 yet at all, so I couldn't tell if you were missing anything.
Kudos for being able to fix the Bacon hackery in `describe_cli`. ✨👍✨ 
(Even with my comment there, I barely understand anymore what this code is doing.)

**Comment by dnkoutso** [comment]
For ruby 3.0 CI failures looks like something related:
```
Bacon::Error: File comparison error `CaPheSuaDa.brewed-coffee` for coffeemaker_no_milk:
--- DIFF -----------------------------------------------------------------------
 class CaPheSuaDa < BrewedCoffee
[31m-  @origin = "Việt Nam"[0m
--- END ------------------------------------------------------------------------
```

Somethign with colored gem?

**Comment by dnkoutso** [comment]
Or maybe that was already there and the new diff with Ruby 3.0 is:
```
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:28
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli.rb:494
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/command.rb:27
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor.rb:392
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli.rb:30
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/base.rb:485
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/cli.rb:24
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/exe/bundle:49
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/lib/bundler/friendly_errors.rb:130
	$HOME/.rvm/gems/ruby-2.6.3/gems/bundler-2.2.8/exe/bundle:37
	$HOME/.rvm/gems/ruby-2.6.3/bin/bundle:23
	$HOME/.rvm/gems/ruby-2.6.3/bin/bundle:23
```

**Comment by dnkoutso** [comment]
Either way would love to unblock this so we can easier bump to Ruby 3.0 in CocoaPods.

**Comment by segiddins** [comment]
Looks like CI isn't running because of the travis changes?

**Comment by dnkoutso** [comment]
@mrackwitz sorry for the ping! Would love to be able to merge this as it can unblock CocoaPods gem updating to Ruby 3.0 for running its tests!

**Comment by mrackwitz** [comment]
@dnkoutso Hey, sorry for the delay. What's not working / blocked right now?

**Comment by dnkoutso** [comment]
@mrackwitz There was an issue that was failing the builds when this PR was opened that @segiddins recently fixed. However, once he pushed a commit CI no longer runs so he cannot verify that his commit works so it can be merged.

**Comment by dnkoutso** [comment]
I think whats left here is to fix CI for this project let this PR run through CI and then merge it if all is green.

**Comment by dnkoutso** [comment]
@mrackwitz hey there, apologies for the second ping, wondering if this can be merged (with CI or without CI). thank you again!

**Comment by dnkoutso** [comment]
tried to add GH actions support https://github.com/mrackwitz/CLIntegracon/pull/29

**Comment by mrackwitz** [comment]
Hey, happy to merge this straight ahead. Sorry, I don't have enough capacity to maintain this at the moment. I've added you as a contributor, but I'm also happy to transfer this repo to the CocoaPods organization.

**Comment by dnkoutso** [comment]
thank you !!!

**Pull request merged**
